export const homeItems = [
  {
    imgUrl: '/img/house-1.jpeg',
    title: 'Beautiful Family House',
    location: 'USA',
    roomCount: 5,
    area: 325,
    price: 1200000,
  },
  {
    imgUrl: '/img/house-2.jpeg',
    title: 'Modern Glass Villa',
    location: 'Canada',
    roomCount: 6,
    area: 450,
    price: 2750000,
  },
  {
    imgUrl: '/img/house-3.jpeg',
    title: 'Cozy Country House',
    location: 'UK',
    roomCount: 4,
    area: 250,
    price: 850000,
  },
  {
    imgUrl: '/img/house-4.jpeg',
    title: 'Large Rustical Villa',
    location: 'Portugal',
    roomCount: 6,
    area: 480,
    price: 1950000,
  },
  {
    imgUrl: '/img/house-5.jpeg',
    title: 'Majestic Palace House',
    location: 'Germany',
    roomCount: 18,
    area: 4239,
    price: 12500000,
  },
  {
    imgUrl: '/img/house-6.jpeg',
    title: 'Modern Family Apartment',
    location: 'Italy',
    roomCount: 3,
    area: 180,
    price: 600000,
  },
];
